//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFIlmaProjekat.ServiceGradFilma {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGradFilma.IGradFilmaService")]
    public interface IGradFilmaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/Login", ReplyAction="http://tempuri.org/IGradFilmaService/LoginResponse")]
        GradFilmaModel.Korisnik Login(GradFilmaModel.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/Login", ReplyAction="http://tempuri.org/IGradFilmaService/LoginResponse")]
        System.Threading.Tasks.Task<GradFilmaModel.Korisnik> LoginAsync(GradFilmaModel.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/Register", ReplyAction="http://tempuri.org/IGradFilmaService/RegisterResponse")]
        void Register(GradFilmaModel.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/Register", ReplyAction="http://tempuri.org/IGradFilmaService/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(GradFilmaModel.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/dajFilmove", ReplyAction="http://tempuri.org/IGradFilmaService/dajFilmoveResponse")]
        System.Collections.Generic.List<GradFilmaModel.Film> dajFilmove();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/dajFilmove", ReplyAction="http://tempuri.org/IGradFilmaService/dajFilmoveResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GradFilmaModel.Film>> dajFilmoveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/dajFilm", ReplyAction="http://tempuri.org/IGradFilmaService/dajFilmResponse")]
        GradFilmaModel.Film dajFilm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/dajFilm", ReplyAction="http://tempuri.org/IGradFilmaService/dajFilmResponse")]
        System.Threading.Tasks.Task<GradFilmaModel.Film> dajFilmAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/dodajFIlm", ReplyAction="http://tempuri.org/IGradFilmaService/dodajFIlmResponse")]
        void dodajFIlm(GradFilmaModel.Film film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/dodajFIlm", ReplyAction="http://tempuri.org/IGradFilmaService/dodajFIlmResponse")]
        System.Threading.Tasks.Task dodajFIlmAsync(GradFilmaModel.Film film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/obrisiFilm", ReplyAction="http://tempuri.org/IGradFilmaService/obrisiFilmResponse")]
        void obrisiFilm(GradFilmaModel.Film film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/obrisiFilm", ReplyAction="http://tempuri.org/IGradFilmaService/obrisiFilmResponse")]
        System.Threading.Tasks.Task obrisiFilmAsync(GradFilmaModel.Film film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/dajKorisnika", ReplyAction="http://tempuri.org/IGradFilmaService/dajKorisnikaResponse")]
        GradFilmaModel.Korisnik dajKorisnika(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/dajKorisnika", ReplyAction="http://tempuri.org/IGradFilmaService/dajKorisnikaResponse")]
        System.Threading.Tasks.Task<GradFilmaModel.Korisnik> dajKorisnikaAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGradFilmaServiceChannel : GradFIlmaProjekat.ServiceGradFilma.IGradFilmaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GradFilmaServiceClient : System.ServiceModel.ClientBase<GradFIlmaProjekat.ServiceGradFilma.IGradFilmaService>, GradFIlmaProjekat.ServiceGradFilma.IGradFilmaService {
        
        public GradFilmaServiceClient() {
        }
        
        public GradFilmaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GradFilmaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GradFilmaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GradFilmaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GradFilmaModel.Korisnik Login(GradFilmaModel.Korisnik korisnik) {
            return base.Channel.Login(korisnik);
        }
        
        public System.Threading.Tasks.Task<GradFilmaModel.Korisnik> LoginAsync(GradFilmaModel.Korisnik korisnik) {
            return base.Channel.LoginAsync(korisnik);
        }
        
        public void Register(GradFilmaModel.Korisnik korisnik) {
            base.Channel.Register(korisnik);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(GradFilmaModel.Korisnik korisnik) {
            return base.Channel.RegisterAsync(korisnik);
        }
        
        public System.Collections.Generic.List<GradFilmaModel.Film> dajFilmove() {
            return base.Channel.dajFilmove();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GradFilmaModel.Film>> dajFilmoveAsync() {
            return base.Channel.dajFilmoveAsync();
        }
        
        public GradFilmaModel.Film dajFilm(int id) {
            return base.Channel.dajFilm(id);
        }
        
        public System.Threading.Tasks.Task<GradFilmaModel.Film> dajFilmAsync(int id) {
            return base.Channel.dajFilmAsync(id);
        }
        
        public void dodajFIlm(GradFilmaModel.Film film) {
            base.Channel.dodajFIlm(film);
        }
        
        public System.Threading.Tasks.Task dodajFIlmAsync(GradFilmaModel.Film film) {
            return base.Channel.dodajFIlmAsync(film);
        }
        
        public void obrisiFilm(GradFilmaModel.Film film) {
            base.Channel.obrisiFilm(film);
        }
        
        public System.Threading.Tasks.Task obrisiFilmAsync(GradFilmaModel.Film film) {
            return base.Channel.obrisiFilmAsync(film);
        }
        
        public GradFilmaModel.Korisnik dajKorisnika(string username) {
            return base.Channel.dajKorisnika(username);
        }
        
        public System.Threading.Tasks.Task<GradFilmaModel.Korisnik> dajKorisnikaAsync(string username) {
            return base.Channel.dajKorisnikaAsync(username);
        }
    }
}
