//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KinoSala
    {
        public KinoSala()
        {
            this.Projekcija = new HashSet<Projekcija>();
            this.Sjediste = new HashSet<Sjediste>();
        }
    
        public int idKinoSala { get; set; }
        public int brojSale { get; set; }
        public int brojMjesta { get; set; }
        public int brojRedova { get; set; }
        public int brojKolona { get; set; }
    
        public virtual ICollection<Projekcija> Projekcija { get; set; }
        public virtual ICollection<Sjediste> Sjediste { get; set; }
    }
}
