//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipMjesta
    {
        public TipMjesta()
        {
            this.Sjediste = new HashSet<Sjediste>();
        }
    
        public int idTipMjesta { get; set; }
        public string nazivMjesta { get; set; }
    
        public virtual ICollection<Sjediste> Sjediste { get; set; }
    }
}
