//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int idKorisnik { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string jmbg { get; set; }
        public string telefon { get; set; }
        public string adresa { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int ulogaId { get; set; }
    
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
        public virtual Uloga Uloga { get; set; }
    }
}
