//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilegije
    {
        public Privilegije()
        {
            this.StavkePrivilegije = new HashSet<StavkePrivilegije>();
        }
    
        public int idPrivilegije { get; set; }
        public int ulogaId { get; set; }
        public string naziv { get; set; }
    
        public virtual Uloga Uloga { get; set; }
        public virtual ICollection<StavkePrivilegije> StavkePrivilegije { get; set; }
    }
}
