//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkePrivilegije
    {
        public int idStavkePrivilegije { get; set; }
        public int privilegijaId { get; set; }
        public string naziv { get; set; }
    
        public virtual Privilegije Privilegije { get; set; }
    }
}
