//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipMjesta
    {
        public TipMjesta()
        {
            this.KinoSala = new HashSet<KinoSala>();
        }
    
        public int idTipMjesta { get; set; }
        public Nullable<int> mjestoZaParove { get; set; }
        public Nullable<int> mjestoZaOsobeSaInv { get; set; }
        public Nullable<int> mjesto { get; set; }
    
        public virtual ICollection<KinoSala> KinoSala { get; set; }
    }
}
