CREATE TABLE [dbo].[TipProjekcije](
	[idTipProjekcije] [int] NOT NULL,
	[2D] [int] NULL,
	[3D] [int] NULL,
	[4D] [int] NULL,
 CONSTRAINT [PK_TipProjekcije] PRIMARY KEY CLUSTERED 
(
	[idTipProjekcije] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

