CREATE TABLE [dbo].[Uloga](
	[idUloga] [int] NOT NULL,
	[naziv] [varchar](20) NULL,
 CONSTRAINT [PK_Uloga] PRIMARY KEY CLUSTERED 
(
	[idUloga] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

